name: Deploy Next.js to AWS

permissions:
  contents: "read"
  id-token: "write"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: |
          npm run build
          npm run open-next

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="app_name=ai-health-assistant" -var="aws_region=${{ vars.AWS_REGION }}"
